### PR TITLE
Allow passing a react-native-paper Theme object to components

### PR DESCRIPTION
**Pull request by matmedev**
This PR adds standard react-native-paper theme attribute support for all exported components to close [#73](https://github.com/web-ridge/react-native-paper-dates/issues/73)

- [x] Add standard theme attribute to `DatePickerModal`
- [x] Add standard theme attribute to `DatePickerModalContent`
- [x] Add standard theme attribute to `TimePickerModal`
- [x] Add standard theme attribute to `TimePicker`
- [x] Add theme handling to all internal components
- [x] Add example how to customize theme for all types of exported components

@RichardLindhout could you please give it a review?

Thank you!

### CODE REVIEW

**Comment by RichardLindhout** [comment]
Looking good but I'm really short in time a.t.m. will look at in a month I think when I have more time available. Sorry for the inconvenience

**Comment by matmedev** [comment]
No problem. Looking forward to read your feedback whenever you have time to check it :)

**Comment by RichardLindhout** [comment]
It would help me a lot if you could maybe resolve the conflicts for faster merging, so maybe if you have some spare time, I would love it!

**Comment by iM-GeeKy** [comment]
I'm going to close due to lack of movement. If it is still applicable, please update and we can readdress it.

**Pull request closed without merging**
