### PR TITLE
Resolved misaligned helper text.

### PR DESCRIPTION
**Pull request by iM-GeeKy**
- [x] Addresses https://github.com/web-ridge/react-native-paper-dates/issues/151

### CODE REVIEW

**Comment by iM-GeeKy** [comment]
Any chance we can get this moved/looked at?

**Comment by iM-GeeKy** [comment]
Issue still remains. Please reopen.

**Comment by RichardLindhout** [comment]
Closed it by accident, will try to look into it but also have to release and really short on time a.t.m. will def merge these things later!

**Comment by iM-GeeKy** [comment]
> Closed it by accident, will try to look into it but also have to release and really short on time a.t.m. will def merge these things later!

Not in a hurry, I have local patch's applied for the time being.

**Comment by RichardLindhout** [comment]
Thank you!

**Pull request merged**
