### PR TITLE
Material You

### PR DESCRIPTION
**Pull request by iM-GeeKy**
- [x] Attempting to move the ball on https://github.com/web-ridge/react-native-paper-dates/issues/189.

@RichardLindhout Any feedback would be appreciated here. It appears react-native-paper will soon get version 5 into stable and this could potentially resolve the following
 - https://github.com/web-ridge/react-native-paper-dates/issues/185
 - https://github.com/web-ridge/react-native-paper-dates/issues/204
 - https://github.com/web-ridge/react-native-paper-dates/issues/200. 

This will seamlessly detect the paper version, so it should be backward compatible with version 2. I've been using a patch of this with a lot of success in my own application and for the longevity of this repo, I think it's paramount this gets accomplished. I'm happy to help where possible, time permitting.

### CODE REVIEW

**Review by thejoaov — APPROVED** [review]

**Comment by bombillazo** [comment]
Im willing to test this with RNP5

**Comment by RichardLindhout** [comment]
Looking good will try to merge this week or next week!

**Comment by bombillazo** [comment]
Has this been released? seems like 0.9.2 doesnt have these changes or am I incorrect?

**Comment by iM-GeeKy** [comment]
> Has this been released? seems like 0.9.2 doesnt have these changes or am I incorrect?

Not to my knowledge, I've still been using `patch-package` in my project.

**Comment by bombillazo** [comment]
Same here, I want to test this PR so I dont have to be patching up, also would try to contribute fixes to this repo itself too

**Comment by rrufus** [comment]
@RichardLindhout Thank you for the work on this library! Wondering what timelines look like for releasing a new version with these merged changes?

I'm having the issue described here: https://github.com/web-ridge/react-native-paper-dates/issues/189#issuecomment-1346987334 and I think releasing a new version with this might fix it?

**Pull request merged**
