### PR TITLE
Add Spanish translations

### PR DESCRIPTION
**Pull request by jess232017**
this pr add spanish translations

### CODE REVIEW

**Comment by iM-GeeKy** [comment]
LGTM. @RichardLindhout I can merge this in the future, but I was curious which option you choose when you merge just to remain consistent with your past process.

**Comment by RichardLindhout** [comment]
We can merge these :)
Ideally we would have some kind of automated proces / github action which runs the `yarn release` thing

**Comment by andresfdaza-accenture** [comment]
Greetings!, regarding this language... I modified the registerTranslation to Spanish, running the application in an emulator with expo everything looks as expected. But in the compiled .apk and .ipa, the days and months appear in English even if the device is on Spanish ( keeping the labels configured in Spanish ) Do you Know What it can be? Or how could I fix that?

**Comment by RichardLindhout** [comment]
You can force the locale with locale prop

**Comment by RichardLindhout** [comment]
https://web-ridge.github.io/react-native-paper-dates/docs/date-picker/single-date-picker#props

**Pull request merged**
