### PR TITLE
PresentationStyle

### PR DESCRIPTION
**Pull request by SharfMohiuddin**
pageSheet

### CODE REVIEW

**Comment by RichardLindhout** [comment]
Looks good! Can you update it with the right prettier? Seems like some things are different (`;` is added)

**Comment by SharfMohiuddin** [comment]
I just used the right prettier in this commit. Kindly, accept the pull request. @RichardLindhout

**Comment by iM-GeeKy** [comment]
@RichardLindhout and @SharfMohiuddin I think we should also add this new prop to the documentation so it is visible to others who might want to use this in the future.

**Comment by SharfMohiuddin** [comment]
I agree with you.  @iM-GeeKy

**Comment by SharfMohiuddin** [comment]
@RichardLindhout kindly accept the pull request. Thanks!

**Comment by iM-GeeKy** [comment]
> I agree with you. @iM-GeeKy

Would you mind updating the docs as part of this pull request? I'll merge it afterward.

**Comment by SharfMohiuddin** [comment]
sure @iM-GeeKy

**Comment by iM-GeeKy** [comment]
@SharfMohiuddin Thanks!

**Pull request merged**
