### PR TITLE
Add Japanese translations

### PR DESCRIPTION
**Pull request by kota113**
Thank you for creating this library! 
As a developer from Japan, I'd like to add Japanese translations to it. 

\* I haven't checked the translation yet. I still need to check whether the translation is appropriate for the usage.

### CODE REVIEW

**Comment by iM-GeeKy** [comment]
@kota113 Here is a another translation [PR](https://github.com/web-ridge/react-native-paper-dates/pull/379/files) as a reference. Make sure to add it to the `docusaurus` and `example` directory files respectively.

**Comment by kota113** [comment]
Thanks!! I'll follow the procedure and add "ja" to them.

**Comment by iM-GeeKy** [comment]
@kota113 Could you update the `App.tsx` to include `ja`? Take a look at this https://github.com/web-ridge/react-native-paper-dates/pull/379/files#diff-6a99c076036be89e153c671ac5e086623e32b13dfa5a46df98293d472c422010

**Review by SoyDiego — APPROVED** [review]

**Comment by kota113** [comment]
It took a while but completed! 
I was a bit busy and couldn't take a time to do this. sry :)

**Pull request merged**
