### PR TITLE
Adding hebrew translation

### PR DESCRIPTION
**Pull request by IlanKro**
Hi, Adding hebrew translations, I used the arabic (an rtl language) as a template, so it should work similarly.
I didn't test if it look right becuase I am not sure how to test only a library, but it should work if Arabic work.
If I have to test it before please tell me how I should do it, thanks :).

### CODE REVIEW

**Comment by iM-GeeKy** [comment]
Hey @IlanKro can you update the [`intro.md` documentation](https://github.com/web-ridge/react-native-paper-dates/pull/225/files#diff-08a63de07975df3aabe4be2c0369a1ece29295f40de36879ac1b11f06041d270) to also include `he`.

**Comment by IlanKro** [comment]
> Hey @IlanKro can you update the [`intro.md` documentation](https://github.com/web-ridge/react-native-paper-dates/pull/225/files#diff-08a63de07975df3aabe4be2c0369a1ece29295f40de36879ac1b11f06041d270) to also include `he`.

done

**Comment by iM-GeeKy** [comment]
@RichardLindhout Can you check this out?

**Review by RichardLindhout — APPROVED** [review]

**Comment by RichardLindhout** [comment]
Looks good!

**Comment by OriGummy** [comment]
Hey @IlanKro , I was wondering how did you get RTL support in the first place?
Seems like the whole UI flips (e.g. TimePicker) when setting RTL project-wide, with no way to exclude the picker component itself.

**Pull request merged**
