### PR TITLE
translate date format

### LINKED ISSUE #232: MM.DD.YYYY needs to be translated
We should use translated letters for this kind of text. For instance, it should be 'GG.AA.YYYY' and it refers to 'DD.MM.YYYY'.

image

### PR DESCRIPTION
**Pull request by mikib0**
Closes #232 

Before:
before

After:
after

### CODE REVIEW

**Comment by mikib0** [comment]
@iM-GeeKy supported translations and maybe [this part](https://web-ridge.github.io/react-native-paper-dates/docs/intro#custom) of the docs may need to be updated right?

**Comment by iM-GeeKy** [comment]
> @iM-GeeKy supported translations and maybe [this part](https://web-ridge.github.io/react-native-paper-dates/docs/intro#custom) of the docs may need to be updated right?

Yeah, that seems like an appropriate spot for it.

**Comment by mikib0** [comment]
The date format length in some locales like ko and ar may not equal the date input text length. For example a date input like 02/01/2023 has equal length with the date format MM/DD/YYYY in the en locale, but it doesn't with the ar date format يوم/شهر/سنة (length = 11). This raises a problem with this condition check [`text.length == mask.length`](https://github.com/web-ridge/react-native-paper-dates/blob/6f1078c80f84f86ce3e36a1cc41c523e68b24b49/src/TextInputMask.tsx#L84) in `TextInputWithMask` component, as the mask length (11 in the case of ar) doesn't equal the date input text length (8). What should we do now?

**Comment by iM-GeeKy** [comment]
> The date format length in some locales like ko and ar may not equal the date input text length. For example a date input like 02/01/2023 has equal length with the date format MM/DD/YYYY in the en locale, but it doesn't with the ar date format يوم/شهر/سنة (length = 11). This raises a problem with this condition check [`text.length == mask.length`](https://github.com/web-ridge/react-native-paper-dates/blob/6f1078c80f84f86ce3e36a1cc41c523e68b24b49/src/TextInputMask.tsx#L84) in `TextInputWithMask` component, as the mask length (11 in the case of ar) doesn't equal the date input text length (8). What should we do now? @iM-GeeKy

Ahh, I think I see what you're talking about. The only thing I can think of off the top of my head is potentially having some sort of getter function to retrieve the right mask length via a switch/case or something of the like. It's not the most elegant solution though, perhaps @RichardLindhout has an idea?

**Comment by RichardLindhout** [comment]
Looks good to me! Maybe we should indeed do some kind of function or put some things outside of the component so we can get the maskLength everywhere. I'm not sure or have the time too check this out deep but update is welcome, and then we can merge!

**Comment by SoyDiego** [comment]
Hi @mikib0, will you continue with this PR or maybe can I help in something to continue it?

Thanks!

**Pull request closed without merging**
