### PR TITLE
Add date range support

### LINKED ISSUE #48: Disable/blur old dates
It would be nice to have a boolean that doesn't allow you to click dates before today (i.e. a `minDate: new Date()`). It could then reduce the opacity of the hidden dates, so users know not to click them.

### PR DESCRIPTION
**Pull request by nandorojo**
Added support for an optional `validRange` prop. Closes #48.

Usage:

```jsx
<DatePickerModal 
  validRange={{
    startDate: new Date(),
    endDate: dateInTheFuture()  
  }}
/>
```

Both `startDate` and `endDate` are optional.

# List

- [x] Disable clicking items not matching range
- [x] Blur items outside of the range
- [x] Make range opt-in only, per-field
- [x] Add `validRange` to example app

### CODE REVIEW

**Comment by RichardLindhout** [comment]
Hey looks good, instead of converting to iso and to date back again to prevent re-rendering the useCallback please use the userLatest hook

**Comment by nandorojo** [comment]
I turned the dates into strings so that the same date would maintain the same reference to `useCallback` across renders. However, if someone updates the actual time for the start or end of the range, then the function should probably receive a new reference altogether. 

I figured this was the desired outcome, since `useCallback` also has other variables in its dependency array which will cause it to create a new reference.

That said, if someone uses `new Date()` directly in render code, it could cause the code to constantly update on every render. So I think your feedback makes sensee.

**Comment by RichardLindhout** [comment]
Yeah I know, but that's exactly what the useLatest hooks solve since it will not re-render since the dependency is a ref!
I like that you think of perfomance since it's indeed slow if the useCallback get re-rendered, but the useLatest hook should solve that issue :)

**Comment by nandorojo** [comment]
Yeah, makes sense.

**Comment by RichardLindhout** [comment]
Yeah should work good https://twitter.com/dan_abramov/status/1063801478584897536. I use useLatest for more things so if it does not work the library is fucked anyway because I use the same trick in other places to prevent re-rendering

**Comment by nandorojo** [comment]
Fixed.

I left it as a string for `Date/Month`, since this memoization is used in render code, not onPress. If we use a ref here, the UI won't update if the range dates change.

**Comment by nandorojo** [comment]
Also included exports to close #47

**Comment by nandorojo** [comment]
@RichardLindhout just confirming that sounds good to you. We should be triggering a re-render if the datetime string changes. Otherwise, changing the valid range would result in stale UI.

**Comment by nandorojo** [comment]
I'm using a fork now in my app, it's all working well.

**Pull request merged**
