### PR TITLE
fix: update input label for pt locale

### PR DESCRIPTION
**Pull request by brandon-eb**
Hello! In Portuguese they use `AAAA` instead of `YYYY` for dates. This PR updates the inputFormat to use `AAAA` when the Portuguese locale is selected.

### CODE REVIEW

**Comment by RichardLindhout** [comment]
Hey Brandon, can you back this up by some external source on wikipedia it says for Portugal: https://en.wikipedia.org/wiki/Date_format_by_country


Portugal | Yes | Yes | No | Mostly (dd/mm/yyyy) and (dd-mm-yyyy); some newer documents use (yyyy-mm-dd).[134] | NP EN 28601
-- | -- | -- | -- | -- | --

**Comment by brandon-eb** [comment]
If you look on the "Date" wikipedia entry in Portuguese you can see they list the date format as AAAA-MM-DD: https://pt.wikipedia.org/wiki/Data

**Comment by RichardLindhout** [comment]
Thanks! Will try to release a new version next week with this fix :)

**Comment by brandon-eb** [comment]
Great! Thanks!

**Comment by brandon-eb** [comment]
@RichardLindhout Any updates on when this will be released? My team would like to include this change in our next release.

**Comment by RichardLindhout** [comment]
I forgot about it, thanks for your PR!

**Pull request merged**
